---
label: Recipe
hide_body: true
fields:
- type: text
  name: name
  label: Name
  description: Paste in the name of the recipe
- type: list
  name: ingredients
  label: Ingredients
  description: Add the ingredients one at a time
- type: list
  name: instructions
  label: Instructions
  description: Add the instructions one line at a time
- type: list
  name: tags
  label: Tags
  description: Tags are made to group recipes by type or ingredient
  config:
    use_select: false
- type: text
  name: servings
  label: Servings
  description: How many people does it serve or how large is the yield in cups, feet,
    meters, stones, etc.
- name: image
  type: file
  config:
    maxSize: 64
  label: Image
  description: Optionally, upload an image representing your recipe.
- type: field_group
  name: time
  label: Times
  fields:
  - type: text
    name: prep
    label: Prep
    description: How long to prepare the recipe?
  - type: text
    name: cook
    label: Cook
    description: How long is spent cooking the recipe?
  - type: text
    name: active
    label: Active
    description: How much time is spent actively working on the recipe?
  - type: text
    name: inactive
    label: Inactive
    description: How much time is spent inactive? e.g. letting the dough rise, chill,
      etc.
  - type: text
    name: ready
    label: Ready
    description: 'How long until it''s ready? '
  - type: text
    name: total
    label: Total
    description: 'What is the total time spent? '
  description: Add any of the available times below
- name: url
  type: text
  config:
    required: false
  label: Original Recipe URL
  description: Paste in the source of the URL if it exists
pages:
- src/_data/recipes/banana-bread.json
- src/_data/recipes/brownie-pudding.json
