---
label: Recipe
hide_body: true
fields:
- type: text
  name: name
  label: name
- type: text
  name: servings
  label: servings
- type: field_group
  name: time
  label: time
  fields:
  - type: text
    name: cook
    label: cook
  - type: text
    name: prep
    label: prep
- type: list
  name: ingredients
  label: ingredients
- type: list
  name: instructions
  label: instructions
